# Site Settings

title: "Reproducible Workflows in RStudio"
email: "cyberhelp@sesync.org"
description: "Learn tools for collaborative and reproducible research."
baseurl: /basic-git-lesson
#styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.0
styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0

# Slide Settings

slide_sorter:
  - title
  - workflows
  - intro
  - goals
  - reproducible
  - github
  - rstudio
  - conclude

# Jekyll Settings

markdown: kramdown
collections:
  - slides
