# Site Settings

title: "Reproducible Workflows in RStudio"
email: "cyberhelp@sesync.org"
description: "Learn tools for collaborative and reproducible research."
baseurl: /basic-git-lesson
styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master

# Slide Settings
slide_sorter:
  - title
  - workflows
  - intro
  - goals
  - reproducible
  - github
  - rstudio
  - conclude

# Jekyll Settings

markdown: kramdown
collections:
  - slides

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
