# Site settings

title: "Basic git Lesson"
email: "icarroll@sesync.org"
description: "Learn tools for collaborative and reproducible research."
baseurl: "/basic-git-lesson"

# Jekyll Settings

markdown: kramdown
collections:
  - slides
slide_sorter:
  - title
  - intro
  - challenges
  - reproducible
  - workflow
  - github
  - git
  - collab
