# Site settings

title: "Collaborative & Reproducible Workflows"
email: "cyberhelp@sesync.org"
description: "Learn tools for collaborative and reproducible research."
baseurl: "/basic-git-lesson"

# Jekyll Settings

markdown: kramdown
collections:
  - slides

# Slide Order
slide_sorter:
  - title
  - intro
  - goals
  - challenges
  - reproducible
  - github
  - git
  - collab
  - conclude
