# Site settings

title: "Collaborative & Reproducible Workflows"
email: "cyberhelp@sesync.org"
description: "Learn tools for collaborative and reproducible research."
baseurl: /basic-git-lesson
styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master

# Jekyll Settings

markdown: kramdown
collections:
  - slides

# Slide Order
slide_sorter:
  - title
  - intro-1
  - intro-2
  - goals
  - challenges
  - reproducible
  - github
  - git
  - collab
  - conclude
