# Lesson

title: Collaborative Workflows & Reproducible Pipelines
handouts: worksheet.sh
tag: v0.0
lesson: 2
instructor: Ian Carroll
authors:
 - Ian Carroll

# Slides

slide_sorter:
  - goals
  - intro
  - reproducible
  - workflows
  - terms
  - repo
  - readme
  - save
  - collab
  - conclude
  
#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/1.1/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0

# Jekyll

markdown: kramdown
collections:
  - slides
