# Site

title: Collaborative Workflows & Reproducible Pipelines
handouts:
  - worksheet.sh
  - worksheet.R
tag: v0.0
lesson: 1
instructor: Ian Carroll
authors:
  - Ian Carroll

# Slides

slide_sorter:
  - goals
  - intro
  - reproducible
  - workflows
  - terms
  - repo
  - config
  - paths
  - collab
  - conclude
  
#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.2/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
