# Site

title: Collaborative Workflows & Reproducible Pipelines
handouts:
  - worksheet.sh
tag: v0.2
lesson: 3
instructor: Quentin Read
example:
  name: J. Doe
  user: jdoe
  email: jdoe@sesync.org
authors:
  - Ian Carroll
  - Quentin Read

# Slides

slide_sorter:
  - intro
  - pipelines
  - goals
  - config
  - terms
  - collab
  - paths
  - reproducible
  - conclude
  
#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v2.0/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
